name: Dev to Release Auto PR & Merge
on:
  push:
    branches:
      - dev

permissions:
  contents: write
  pull-requests: write

jobs:
  create-and-merge-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create Pull Request (dev → release)
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.BOT_PAT_TOKEN }}
          commit-message: "chore: sync dev to release"
          branch: dev
          base: release
          title: "chore: Merge dev to release [automated]"
          body: |
            ## Automated merge from dev to release

            Triggered by push to dev by: ${{ github.actor }}

            [View commit details](https://github.com/${{ github.repository }}/commit/${{ github.sha }})
          labels: auto-merge, automated
          draft: false

      - name: Enable Auto-merge
        if: steps.cpr.outputs.pull-request-url
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: merge
          token: ${{ secrets.BOT_PAT_TOKEN }}

      - name: Auto-approve PR
        if: steps.cpr.outputs.pull-request-url
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.BOT_PAT_TOKEN }}

      - name: Output PR Info
        if: steps.cpr.outputs.pull-request-url
        run: |
          echo "✅ Auto PR created: ${{ steps.cpr.outputs.pull-request-url }}"
